"""Report endpoints.

A report is generated by a worker and *read* here. There is deliberately no
`GET /reports/generate` that produces one inline:  makes a report a first-class object
with provenance and a review gate, and a synchronous endpoint would make it a rendering of
whatever the database held at request time -- which is the thing that cannot be audited.

**Reads are scoped to the principal the report was generated for.** A report is a view of a
session through one person's visibility; handing it to a second person hands them the first
person's view. An overseer-grade `read_any_manifest` holder may read across, the same
action and the same reasoning context manifests use -- one notion of "may see
another principal's derived artefact", not two.
"""

from __future__ import annotations

import uuid

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response
from pydantic import BaseModel

from api.blob_store_factory import get_blob_store
from api.job_queue_factory import get_job_queue
from api.middleware.auth import get_request_context
from api.middleware.rate_limit import rate_limit_by_principal, rate_limit_by_tenant
from api.permission_service_factory import get_permission_service
from core.agents.models import Persona
from core.ports.blob_store import BlobNotFoundError
from core.ports.permission import UnknownActionError
from core.process.authoring import get_definition
from core.process.dsl.schema import ProcessDefinitionDSL
from core.reporting.pipeline import ReportRow, get_report, mark_reviewed
from core.reporting.templates import BUILT_IN_TEMPLATES, get_template
from core.sessions.lifecycle import get_session
from core.tenancy.context import RequestContext
from core.tenancy.scope import tenant_scope

router = APIRouter(
    prefix="/reports",
    tags=["reports"],
    dependencies=[
        Depends(get_request_context),
        Depends(rate_limit_by_principal),
        Depends(rate_limit_by_tenant),
    ],
)

_READ_ANY_ACTION = "read_any_manifest"


class TemplateResponse(BaseModel):
    key: str
    label_key: str
    audience_mode: str
    output_formats: list[str]
    requires_review: bool


@router.get("/templates")
async def list_templates() -> list[TemplateResponse]:
    return [
        TemplateResponse(
            key=t.key,
            label_key=t.label_key,
            audience_mode=t.audience_mode,
            output_formats=list(t.output_formats),
            requires_review=t.requires_review,
        )
        for t in BUILT_IN_TEMPLATES.values()
    ]


class GenerateReportRequest(BaseModel):
    session_id: uuid.UUID
    template_key: str


class GenerateReportResponse(BaseModel):
    job_id: uuid.UUID
    template_key: str
    audience_mode: str
    from_event_seq: int
    to_event_seq: int


@router.post("", status_code=202)
async def request_report(
    body: GenerateReportRequest, ctx: RequestContext = Depends(get_request_context)
) -> GenerateReportResponse:
    """Generated **for the calling principal**, always. There is no "generate for" -- a
    report is a view through one person's visibility, and naming someone else would make
    this a way to see what they see."""
    try:
        template = get_template(body.template_key)
    except KeyError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc

    sess = await get_session(ctx.tenant_id, body.session_id)
    if sess is None:
        raise HTTPException(status_code=404, detail=f"no session {body.session_id}")

    phase = await _phase_of(ctx.tenant_id, sess)
    async with tenant_scope(ctx.tenant_id) as session:
        agent = await session.get(Persona, sess.persona_id)
        if agent is None:
            raise HTTPException(status_code=409, detail="session's agent no longer exists")
        agent_id = agent.agent_id

    to_event_seq = max(sess.next_event_seq - 1, 0)
    job_id = await get_job_queue().enqueue(
        ctx.tenant_id,
        "generate_report",
        {
            "tenant_id": str(ctx.tenant_id),
            "workspace_id": str(sess.workspace_id),
            "session_id": str(body.session_id),
            "viewer_principal_id": str(ctx.principal_id),
            "agent_id": str(agent_id),
            "template_key": template.key,
            "phase": phase,
            "from_event_seq": 0,
            "to_event_seq": to_event_seq,
        },
    )
    return GenerateReportResponse(
        job_id=job_id,
        template_key=template.key,
        audience_mode=template.audience_mode,
        from_event_seq=0,
        to_event_seq=to_event_seq,
    )


class ReportResponse(BaseModel):
    id: uuid.UUID
    session_id: uuid.UUID
    template_key: str
    audience_mode: str
    content_md: str
    redactions: list[dict[str, object]]
    artifacts: dict[str, object]
    fact_frame_hash: str
    source_event_range: list[int]
    reviewed_by: uuid.UUID | None


def _to_response(row: ReportRow) -> ReportResponse:
    return ReportResponse(
        id=row.id,
        session_id=row.session_id,
        template_key=row.template_key,
        audience_mode=row.audience_mode,
        content_md=row.content_md,
        redactions=row.redactions,
        artifacts=row.artifacts,
        fact_frame_hash=row.fact_frame_hash,
        source_event_range=[row.source_event_from, row.source_event_to],
        reviewed_by=row.reviewed_by,
    )


@router.get("")
async def list_session_reports(
    session_id: uuid.UUID, ctx: RequestContext = Depends(get_request_context)
) -> list[ReportResponse]:
    """Reports for one session, newest first (authorization mirrors the by-id read:
    each row passes the same read check; rows the caller may not read are skipped)."""
    from core.reporting.pipeline import list_reports_for_session

    rows = await list_reports_for_session(ctx.tenant_id, session_id)
    out: list[ReportResponse] = []
    for row in rows:
        try:
            await _authorised_report(ctx, row.id)
        except HTTPException:
            continue
        out.append(_to_response(row))
    return out


@router.get("/{report_id}")
async def read_report(
    report_id: uuid.UUID, ctx: RequestContext = Depends(get_request_context)
) -> ReportResponse:
    row = await _authorised_report(ctx, report_id)
    return _to_response(row)


@router.post("/{report_id}/review", status_code=200)
async def review_report(
    report_id: uuid.UUID, ctx: RequestContext = Depends(get_request_context)
) -> ReportResponse:
    """Marking a report reviewed is what unlocks its artifacts for a template that
    requires it. Only a principal who may *read* the report may review it --
    approving something you cannot see is a signature on a blank page."""
    await _authorised_report(ctx, report_id)
    await mark_reviewed(ctx.tenant_id, report_id, ctx.principal_id)
    return await read_report(report_id, ctx)


async def _authorised_report(ctx: RequestContext, report_id: uuid.UUID) -> ReportRow:
    row = await get_report(ctx.tenant_id, report_id)
    if row is None:
        raise HTTPException(status_code=404, detail=f"no report {report_id}")
    if row.generated_for_principal_id == ctx.principal_id:
        return row

    sess = await get_session(ctx.tenant_id, row.session_id)
    if sess is None:
        raise HTTPException(status_code=404, detail=f"no report {report_id}")
    try:
        granted = await get_permission_service().check(
            ctx.tenant_id, ctx.principal_id, _READ_ANY_ACTION, "workspace", sess.workspace_id
        )
    except UnknownActionError:
        granted = False
    if not granted:
        raise HTTPException(
            status_code=403,
            detail="a report is a view through one principal's visibility; reading "
            "another's needs an overseer-grade permission",
        )
    return row


async def _phase_of(tenant_id: uuid.UUID, sess: object) -> dict[str, object]:
    """The session's current phase, serialised for the job payload. A session with no
    process definition has no declared visibility to report against, and guessing one
    would be inventing the very rule the pipeline is supposed to obey."""
    definition_id = getattr(sess, "process_definition_id", None)
    if definition_id is None:
        raise HTTPException(
            status_code=409,
            detail="this session runs no process definition, so it declares no visibility "
            "for a report to be filtered against",
        )
    definition_row = await get_definition(tenant_id, definition_id)
    if definition_row is None:
        raise HTTPException(status_code=409, detail="the session's pinned definition is gone")
    definition = ProcessDefinitionDSL.model_validate(definition_row.definition)
    phase = definition.phases.get(str(getattr(sess, "current_phase", "")))
    if phase is None:
        raise HTTPException(
            status_code=409, detail="the session's current phase is not in its definition"
        )
    return dict(phase.model_dump(mode="json", by_alias=True))


# ── rendering + downloads ────────────────────────────────────────────────────


class RenderRequest(BaseModel):
    output_format: str


class RenderResponse(BaseModel):
    job_id: uuid.UUID
    output_format: str


@router.post("/{report_id}/render", status_code=202)
async def request_render(
    report_id: uuid.UUID,
    body: RenderRequest,
    ctx: RequestContext = Depends(get_request_context),
) -> RenderResponse:
    """Rendering is authorised as a *read* of the report: producing another copy of
    something in a different file format is not a lesser act than reading it."""
    row = await _authorised_report(ctx, report_id)
    template = get_template(row.template_key)
    if body.output_format not in template.output_formats:
        raise HTTPException(
            status_code=422,
            detail=f"template {template.key!r} declares formats "
            f"{list(template.output_formats)}; {body.output_format!r} is not one of them",
        )
    job_id = await get_job_queue().enqueue(
        ctx.tenant_id,
        "render_report",
        {
            "tenant_id": str(ctx.tenant_id),
            "report_id": str(report_id),
            "output_format": body.output_format,
        },
    )
    return RenderResponse(job_id=job_id, output_format=body.output_format)


@router.get("/{report_id}/artifacts/{output_format}")
async def download_artifact(
    report_id: uuid.UUID,
    output_format: str,
    ctx: RequestContext = Depends(get_request_context),
) -> Response:
    """The review gate lives here, not in the renderer: a review-required report *renders*
    (with its DRAFT notice, so a reviewer can read what they are approving) but does not
    *download* until reviewed. Gating the render instead would mean a reviewer had nothing
    to review."""
    row = await _authorised_report(ctx, report_id)
    template = get_template(row.template_key)
    if template.requires_review and row.reviewed_at is None:
        raise HTTPException(
            status_code=409,
            detail=f"template {template.key!r} requires review before its artifacts are "
            "downloadable; this report has not been reviewed",
        )

    artifact = dict(row.artifacts).get(output_format)
    if not isinstance(artifact, dict):
        raise HTTPException(
            status_code=404,
            detail=f"report {report_id} has no {output_format} artifact yet; render it first",
        )

    try:
        data = await get_blob_store().get(str(artifact["blob_key"]))
    except BlobNotFoundError as exc:
        raise HTTPException(status_code=410, detail="the rendered artifact is gone") from exc

    return Response(
        content=data,
        media_type=str(artifact["media_type"]),
        headers={
            "Content-Disposition": (f'attachment; filename="report-{report_id}.{output_format}"')
        },
    )
