"""Report generation job (G4.10) -- the worker-side wiring `core.reporting.pipeline` needs
but can't import itself (composition root: which `ModelProvider` and `PermissionService`).
Registered in `worker.main` under kind `"generate_report"`.

A report is generated by a worker, not by a download endpoint (§11.5). That is not a
performance decision: it is what makes a report a first-class *object* with provenance and
a review gate, rather than a rendering of whatever the database happened to hold when
someone clicked.

Idempotent on (session, viewer, template, range): re-running a delivered job returns the
same report rather than generating a second one that says the same thing with different
words and a different id.
"""

from __future__ import annotations

import uuid
from typing import Any

from adapters.permission.role_permission import RolePermissionService
from core.actions.idempotency import idempotent
from core.agents.models import Agent
from core.process.dsl.schema import PhaseSpec
from core.reporting.pipeline import generate_report
from core.reporting.templates import get_template
from core.tenancy.models import Principal
from core.tenancy.scope import tenant_scope
from worker.model_provider_factory import get_model_provider


def _report_job_key(**kwargs: Any) -> str:
    return (
        f"generate_report:{kwargs['session_id']}:{kwargs['viewer_principal_id']}:"
        f"{kwargs['template_key']}:{kwargs['from_event_seq']}-{kwargs['to_event_seq']}"
    )


@idempotent(key_fn=_report_job_key)
async def run_report_job(
    *,
    tenant_id: uuid.UUID,
    workspace_id: uuid.UUID,
    session_id: uuid.UUID,
    viewer_principal_id: uuid.UUID,
    agent_id: uuid.UUID,
    template_key: str,
    phase: dict[str, Any],
    from_event_seq: int,
    to_event_seq: int,
) -> dict[str, Any]:
    async with tenant_scope(tenant_id) as session:
        viewer = await session.get(Principal, viewer_principal_id)
        if viewer is None:
            raise ValueError(f"no principal {viewer_principal_id} in this tenant")
        agent = await session.get(Agent, agent_id)
        if agent is None:
            raise ValueError(f"no agent {agent_id} in this tenant")
        session.expunge(viewer)
        session.expunge(agent)

    result = await generate_report(
        tenant_id,
        workspace_id,
        session_id,
        viewer,
        PhaseSpec.model_validate(phase),
        get_template(template_key),
        from_event_seq=from_event_seq,
        to_event_seq=to_event_seq,
        agent=agent,
        provider=get_model_provider(agent.provider),
        permission_service=RolePermissionService(),
    )
    return {
        "report_id": str(result.report_id),
        "fact_count": len(result.fact_frame.facts),
        "fact_frame_hash": result.fact_frame.content_hash,
        "redaction_count": len(result.redactions),
    }


async def handle_generate_report(payload: dict[str, Any]) -> dict[str, Any]:
    return await run_report_job(
        tenant_id=uuid.UUID(payload["tenant_id"]),
        workspace_id=uuid.UUID(payload["workspace_id"]),
        session_id=uuid.UUID(payload["session_id"]),
        viewer_principal_id=uuid.UUID(payload["viewer_principal_id"]),
        agent_id=uuid.UUID(payload["agent_id"]),
        template_key=str(payload["template_key"]),
        phase=payload["phase"],
        from_event_seq=int(payload["from_event_seq"]),
        to_event_seq=int(payload["to_event_seq"]),
    )
